# THIS CODE IS NOT FINISHED. NOT ALL REFERENCES ARE WRITTEN.
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# Creating Hotel Chains table
CREATE TABLE Chains (ID INT NOT NULL AUTO_INCREMENT,
ChainName VARCHAR(100) NOT NULL, TypeName VARCHAR(100) NOT NULL,
DirectorsFirstName VARCHAR(100) NOT NULL, DirectorsLastName VARCHAR(100) NOT NULL, DirectorsPatronymic VARCHAR(100) NULL,
PRIMARY KEY (ID));

# Creating Provisioners_Hotels Table (N-M connection)
CREATE TABLE Provisioners_Hotels (ProvisionerID INT NOT NULL, HotelID INT NOT NULL);

# Creating Provisioners Table
CREATE TABLE Provisioners (ID INT NOT NULL AUTO_INCREMENT,
ProvisionersName VARCHAR(100) NOT NULL, ProductOrService VARCHAR(100) NOT NULL,
HotelID INT NULL,
PRIMARY KEY (ID),
FOREIGN KEY FK_HotelID (HotelID) REFERENCES Provisioners_Hotels (HotelID));

# Creating Hotels Table
CREATE TABLE Hotels (ID INT NOT NULL AUTO_INCREMENT, 
HotelName VARCHAR(100) NOT NULL, Address VARCHAR(100) NOT NULL, AddressCategory VARCHAR(100) NOT NULL, # Center or Distance or Aeroport
ChainID INT NOT NULL,
ArrivalTime TIME NULL, DepartureTime TIME NULL,
Stars INT NULL, NumberOfRooms INT NOT NULL,
RoomServiceIncluded BOOL NULL,
FurnitureProvisionerID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY FK_ChainID (ChainID) REFERENCES Chains (ID),
FOREIGN KEY FK_FurnitureProvisionerID (FurnitureProvisionerID) REFERENCES Provisioners_Hotels (ProvisionerID));

# Creating Rooms table
CREATE TABLE Rooms (ID INT NOT NULL AUTO_INCREMENT,
RoomNumber INT NOT NULL, Category VARCHAR (50),
Price FLOAT NOT NULL, Capacity INT NOT NULL,
BedWidth INT NULL,# 120 or 140/140 or 180
BathIncluded BOOL NULL, ShowerIncluded BOOL NULL, JacuzziIncluded BOOL NULL,
MiniBar BOOL NULL, MiniKitchenIncluded BOOL NULL, 
InternetIncluded BOOL NULL, TerraceIncluded BOOL NULL,
ConnectionRoomID INT NULL,
HotelID INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY FK_HotelID (HotelID) REFERENCES Hotels (ID));

# THIS CODE IS NOT FINISHED. NOT ALL REFERENCES ARE WRITTEN.
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET
# DO NOT RUN THIS CODE AND DO NOT FILL THE DATABASE YET